#配置端口
server:
  port: 8088
#配置rabbitMQ
spring:
  rabbitmq:
    port: 5672
    username: guest
    password: guest
    host: 127.0.0.1
    virtual-host: /
#自定义
mq:
  topic:
    exchangName: linux.topic